application: redditwalls
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: static/images

- url: /html/rsc
  static_dir: html/rsc

- url: /.*
  script: redditwalls.application



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
